### ISSUE TITLE
Define website specifications

### ISSUE THREAD

**Issue by trallard** [pyladies/website-redesign#1]
### Additional context

We need to define the requirements for the new website.
These are compiled in the following Document: https://docs.google.com/document/d/1HJcKdVI8WzySoidcRgjzqpCeFHSX4KaMnQHa1ER9mz0/edit?usp=sharing

**Comment by willingc** [comment]
Quick reference image of the spec document's categories:

<img width="270" alt="Screenshot 2024-05-22 at 10 42 48 AM" src="https://github.com/pyladies/website-redesign/assets/2680980/a9b296ed-7753-4b86-b61c-f47073790ddb">

**Comment by trallard** [comment]
Closing this as complete for now as we are moving onto design work based on community feedback

**Comment by willingc** [comment]
Hi @trallard. Is there a place that the design work can be followed? Was the community feedback compiled somewhere? Thanks!

**Comment by trallard** [comment]
Hey @willingc Yes I have yet to open an issue here where we will be posting updates about the design progress and next steps. 

Community feedback remains in the same Google doc as linked above.
