### ISSUE TITLE
[Redesign] Accesbility and Responsivity

### ISSUE THREAD

**Issue by tiidadavena** [pyladies/website-redesign#4]
In order to assure to have both a11y and responsivity to the redesigned website, it would be great to have Figma specifications. For this purpose, the Free version would suit all of needs.

I can help to build some rough components, but it would be awesome to recruit members from [Ladies that UX](https://www.linkedin.com/company/ladies-that-ux/), for example and/or recruit female and nb UX designers to join forces as well. I can also review and test the accessbility issues - specifically regarding [WCAG](https://www.w3.org/TR/WCAG21/) specs.

Another point is to build a real inclusive web experience, a11y and responsivity must part of the project since Day 1.

**Comment by willingc** [comment]
Good suggestion @tiidadavena. Figma is helpful for both ideation and specs. Definitely accessibility and mobile responsive design.

**Comment by trallard** [comment]
Heya! We already have two accessibility UX designers on board to work through the wireframes/prototypes and design documentation for the website redesign. 
Additionally, based on their experience with open-source projects and communities, we'd already planned to have all the designs on Figma and guide discussions/feedback in this repository as we work through these. Eventually, we will add design-specific docs to the kit/website.

**Comment by tiidadavena** [comment]
> Heya! We already have two accessibility UX designers on board to work through the wireframes/prototypes and design documentation for the website redesign. Additionally, based on their experience with open-source projects and communities, we'd already planned to have all the designs on Figma and guide discussions/feedback in this repository as we work through these. Eventually, we will add design-specific docs to the kit/website.

That's great news! Looking foward to check it out :D

**Comment by trallard** [comment]
Since we have the spec doc with this item already I will close this issue so that we can track requirements in one single place vs having similar conversations across different places.
